#!/usr/bin/env bash
# Hypercraft 一键安装 / 启动
# 默认：从 GitHub Releases 下载预编译（无需本机编译）
#
# 用法：
#   ./install.sh              # 下载预编译并启动
#   ./install.sh --docker     # Docker Compose
#   ./install.sh --build      # 本机 cargo/pnpm 编译
#   ./install.sh --env-only
#   ./install.sh --down
#   ./install.sh --logs
#   ./install.sh --no-download  # 用已有 dist/

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"
RUN_DIR="$ROOT/data/run"
LOG_DIR="$ROOT/data/logs"
CACHE_DIR="$ROOT/data/cache"
DIST_BACKEND="$ROOT/dist/backend"
DIST_WEB="$ROOT/dist/web"
REPO="${HC_REPO:-Bkm016/hypercraft}"
RELEASE_TAG="${HC_RELEASE_TAG:-main}"
RELEASE_BASE="https://github.com/${REPO}/releases/download/${RELEASE_TAG}"

MODE="binary"
DO_DOWN=0
DO_LOGS=0
NO_DOWNLOAD=0

for arg in "$@"; do
  case "$arg" in
    --docker|-d) MODE="docker" ;;
    --build|-b) MODE="build" ;;
    --binary) MODE="binary" ;;
    --env-only) MODE="env" ;;
    --down) DO_DOWN=1 ;;
    --logs) DO_LOGS=1 ;;
    --no-download) NO_DOWNLOAD=1 ;;
    -h|--help)
      sed -n '2,14p' "$0"
      exit 0
      ;;
    *)
      echo "未知参数: $arg" >&2
      exit 1
      ;;
  esac
done

log()  { printf '\033[36m[install]\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[install]\033[0m %s\n' "$*"; }
die()  { printf '\033[31m[install]\033[0m %s\n' "$*" >&2; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1 || die "缺少命令: $1"; }

rand_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n' | tr '+/' 'Aa' | head -c 48
    return
  fi
  head -c 64 /dev/urandom | base64 | tr -d '\n' | tr '+/' 'Aa' | head -c 48
}

env_get() {
  local key="$1" file="$ROOT/.env"
  [[ -f "$file" ]] || { echo ""; return; }
  grep -E "^\s*${key}=" "$file" | head -1 | cut -d= -f2- | tr -d '[:space:]' || true
}

env_set() {
  local key="$1" value="$2" file="$ROOT/.env"
  if grep -qE "^\s*${key}=" "$file" 2>/dev/null; then
    sed -i.bak "s|^[[:space:]]*${key}=.*|${key}=${value}|" "$file"
    rm -f "${file}.bak"
  else
    echo "${key}=${value}" >> "$file"
  fi
}

ensure_dirs() {
  mkdir -p "$ROOT/data" "$ROOT/services" "$RUN_DIR" "$LOG_DIR" "$CACHE_DIR" \
    "$DIST_BACKEND" "$DIST_WEB"
}

ensure_env() {
  local env_file="$ROOT/.env" example="$ROOT/.env.example"
  [[ -f "$example" ]] || die "缺少 .env.example"
  if [[ ! -f "$env_file" ]]; then
    cp "$example" "$env_file"
    ok "已创建 .env"
  fi
  [[ -n "$(env_get HC_DEV_TOKEN)" ]] || { env_set HC_DEV_TOKEN "$(rand_secret)"; ok "已生成 HC_DEV_TOKEN"; }
  [[ -n "$(env_get HC_JWT_SECRET)" ]] || { env_set HC_JWT_SECRET "$(rand_secret)"; ok "已生成 HC_JWT_SECRET"; }
  if [[ -z "$(env_get HC_ALLOWED_CWD_PREFIXES)" ]]; then
    env_set HC_ALLOWED_CWD_PREFIXES "$ROOT/services"
    ok "已设置 HC_ALLOWED_CWD_PREFIXES"
  fi
  local api_url
  api_url="$(env_get NEXT_PUBLIC_API_URL)"
  api_url="${api_url:-http://localhost:8080}"
  if [[ -d "$ROOT/web" ]]; then
    echo "NEXT_PUBLIC_API_URL=${api_url}" > "$ROOT/web/.env.local"
  fi
}

write_web_config() {
  local web_dir="$1"
  local api_url
  api_url="$(env_get NEXT_PUBLIC_API_URL)"
  api_url="${api_url:-http://localhost:8080}"
  mkdir -p "$web_dir/public"
  cat > "$web_dir/public/config.js" <<EOF
// Generated by install.sh
window.__RUNTIME_CONFIG__ = {
  apiUrl: "${api_url}",
};
EOF
}

print_creds() {
  local token port_web port_api
  token="$(env_get HC_DEV_TOKEN)"
  port_web="$(env_get HC_WEB_PORT)"; port_web="${port_web:-3000}"
  port_api="$(env_get HC_API_PORT)"; port_api="${port_api:-8080}"
  echo
  ok "安装配置就绪"
  log "面板:    http://localhost:${port_web}"
  log "API:     http://localhost:${port_api}"
  log "超管口令(HC_DEV_TOKEN): ${token}"
  warn "请妥善保存超管口令；勿把 .env 提交到 Git"
  echo
}

compose() {
  if docker compose version >/dev/null 2>&1; then docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then docker-compose "$@"
  else die "需要 Docker Compose"
  fi
}

docker_ready() {
  command -v docker >/dev/null 2>&1 || return 1
  docker info >/dev/null 2>&1
}

stop_local() {
  for name in api web; do
    local pid_file="$RUN_DIR/${name}.pid"
    [[ -f "$pid_file" ]] || continue
    local pid
    pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null; then
      log "停止本地 $name (PID $pid)"
      kill "$pid" 2>/dev/null || true
      sleep 0.3
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$pid_file"
  done
}

download_release() {
  local name="$1"
  local url="${RELEASE_BASE}/${name}"
  local out="${CACHE_DIR}/${name}"
  if [[ "$NO_DOWNLOAD" -eq 1 && -f "$out" ]]; then
    log "使用缓存: $out"
    echo "$out"
    return
  fi
  log "下载 $name …"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --retry 3 -o "$out" "$url" || die "下载失败: $url"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$out" "$url" || die "下载失败: $url"
  else
    die "需要 curl 或 wget"
  fi
  echo "$out"
}

extract_flat() {
  local archive="$1" dest="$2"
  rm -rf "$dest"
  local tmp
  tmp="$(mktemp -d "${CACHE_DIR}/extract.XXXXXX")"
  case "$archive" in
    *.zip)
      need_cmd unzip
      unzip -q "$archive" -d "$tmp"
      ;;
    *.tar.gz|*.tgz)
      tar -xzf "$archive" -C "$tmp"
      ;;
    *)
      die "未知压缩格式: $archive"
      ;;
  esac
  # 若只有一层目录则上提
  local count
  count="$(find "$tmp" -mindepth 1 -maxdepth 1 | wc -l | tr -d ' ')"
  if [[ "$count" == "1" ]] && [[ -d "$(find "$tmp" -mindepth 1 -maxdepth 1)" ]]; then
    mv "$(find "$tmp" -mindepth 1 -maxdepth 1)" "$dest"
  else
    mkdir -p "$dest"
    mv "$tmp"/* "$dest"/ 2>/dev/null || true
    mv "$tmp"/.* "$dest"/ 2>/dev/null || true
  fi
  rm -rf "$tmp"
}

api_bin() {
  if [[ -x "$DIST_BACKEND/hypercraft-api" ]]; then echo "$DIST_BACKEND/hypercraft-api"; return; fi
  if [[ -x "$ROOT/backend/target/release/hypercraft-api" ]]; then
    echo "$ROOT/backend/target/release/hypercraft-api"; return
  fi
  echo ""
}

start_local() {
  stop_local
  local bin
  bin="$(api_bin)"
  [[ -n "$bin" ]] || die "未找到 hypercraft-api"
  [[ -f "$DIST_WEB/server.js" || -f "$ROOT/web/node_modules/next/dist/bin/next" ]] || die "未找到 Web"

  local web_port
  web_port="$(env_get HC_WEB_PORT)"; web_port="${web_port:-3000}"

  if [[ -d "$DIST_WEB" ]]; then
    write_web_config "$DIST_WEB"
  fi

  log "启动 API…"
  (
    cd "$ROOT"
    nohup "$bin" >>"$LOG_DIR/api.log" 2>&1 &
    echo $! >"$RUN_DIR/api.pid"
  )

  log "启动 Web (port $web_port)…"
  if [[ -x "$DIST_WEB/node" && -f "$DIST_WEB/server.js" ]]; then
    (
      cd "$DIST_WEB"
      export PORT="$web_port" HOSTNAME=0.0.0.0
      nohup ./node server.js >>"$LOG_DIR/web.log" 2>&1 &
      echo $! >"$RUN_DIR/web.pid"
    )
  elif [[ -f "$DIST_WEB/server.js" ]]; then
    need_cmd node
    (
      cd "$DIST_WEB"
      export PORT="$web_port" HOSTNAME=0.0.0.0
      nohup node server.js >>"$LOG_DIR/web.log" 2>&1 &
      echo $! >"$RUN_DIR/web.pid"
    )
  else
    need_cmd pnpm
    (
      cd "$ROOT/web"
      nohup pnpm exec next start -p "$web_port" -H 0.0.0.0 >>"$LOG_DIR/web.log" 2>&1 &
      echo $! >"$RUN_DIR/web.pid"
    )
  fi

  ok "本地进程已启动"
  log "日志: $LOG_DIR"
  log "停止: ./install.sh --down"
}

install_binary() {
  if [[ "$NO_DOWNLOAD" -eq 0 ]]; then
    local backend_pkg web_pkg
    backend_pkg="$(download_release hypercraft-backend-debian.tar.gz)"
    web_pkg="$(download_release web-standalone-debian.tar.gz)"
    log "解压后端…"
    extract_flat "$backend_pkg" "$DIST_BACKEND"
    chmod +x "$DIST_BACKEND/hypercraft-api" "$DIST_BACKEND/hypercraft-cli" 2>/dev/null || true
    log "解压 Web…"
    extract_flat "$web_pkg" "$DIST_WEB"
    chmod +x "$DIST_WEB/node" "$DIST_WEB/start.sh" 2>/dev/null || true
  else
    log "跳过下载，使用 dist/"
  fi
  [[ -x "$(api_bin)" ]] || die "dist/backend 无 hypercraft-api"
  [[ -f "$DIST_WEB/server.js" ]] || die "dist/web 无 server.js"
  start_local
}

install_build() {
  need_cmd cargo
  need_cmd node
  if ! command -v pnpm >/dev/null 2>&1; then
    need_cmd corepack
    corepack enable
    corepack prepare pnpm@10.15.1 --activate
  fi
  need_cmd pnpm
  log "编译 API…"
  (cd "$ROOT/backend" && cargo build --release -p hypercraft-api -p hypercraft-cli)
  log "构建 Web…"
  (cd "$ROOT/web" && pnpm install && NEXT_TELEMETRY_DISABLED=1 pnpm build)
  mkdir -p "$DIST_BACKEND"
  cp "$ROOT/backend/target/release/hypercraft-api" "$DIST_BACKEND/"
  cp "$ROOT/backend/target/release/hypercraft-cli" "$DIST_BACKEND/" 2>/dev/null || true
  chmod +x "$DIST_BACKEND/"*
  start_local
}

ensure_dirs
ensure_env

if [[ "$DO_DOWN" -eq 1 ]]; then
  docker_ready && compose down || true
  stop_local
  ok "已停止"
  exit 0
fi

if [[ "$DO_LOGS" -eq 1 ]]; then
  docker_ready && compose logs -f || true
  log "跟踪 data/logs"
  tail -F "$LOG_DIR/api.log" "$LOG_DIR/web.log" 2>/dev/null || true
  exit 0
fi

if [[ "$MODE" == "env" ]]; then
  print_creds
  log "默认(预编译): ./install.sh"
  log "Docker:       ./install.sh --docker"
  log "本机编译:     ./install.sh --build"
  exit 0
fi

case "$MODE" in
  docker)
    need_cmd docker
    docker_ready || die "Docker 未运行。可改用: ./install.sh"
    log "Docker Compose 启动…"
    compose up -d --build
    ;;
  build)
    log "本机源码编译…"
    install_build
    ;;
  *)
    log "使用 GitHub Release 预编译（无需本机编译）"
    install_binary
    ;;
esac

print_creds
log "业务服务目录: $ROOT/services"
log "数据目录:     $ROOT/data"
log "预编译目录:   $ROOT/dist"
