#!/bin/sh
# 启动前按环境变量写入 runtime config.js（浏览器侧 API 地址）
set -eu

API_URL="${NEXT_PUBLIC_API_URL:-http://localhost:8080}"
mkdir -p /app/public

cat > /app/public/config.js <<EOF
// Generated by docker/entrypoint-web.sh — do not edit in container
window.__RUNTIME_CONFIG__ = {
  apiUrl: "${API_URL}",
};
EOF

exec node server.js
